---
- name: Converge
  hosts: all
  become: yes
  vars:
    ssh_enabled: yes

  roles:
    - role: role-ssh
      ssh_enabled: true
      #ssh_use_ldap: yes
  
      ssh_sshd_config:
        AllowTcpForwarding: 'no'
        AuthorizedKeysFile: '%h/.ssh/authorized_keys'
        ClientAliveCountMax: 0
        ClientAliveInterval: 0
        HostbasedAuthentication: 'no'
        HostKey:
          - /etc/ssh/ssh_host_ed25519_key
          - /etc/ssh/ssh_host_rsa_key
        IgnoreRhosts: 'yes'
        LoginGraceTime: 60s
        LogLevel: INFO
        PasswordAuthentication: 'no'
        PermitEmptyPasswords: 'no'
        PermitRootLogin: 'prohibit-password'
        Port: 22
        PrintLastLog: 'yes'
        PrintMotd: 'no'
        Protocol: 2
        PubkeyAuthentication: 'yes'
        PermitUserEnvironment: 'no'
        StrictModes: 'yes'
        'Subsystem sftp': /usr/lib/openssh/sftp-server
        SyslogFacility: AUTH
        TCPKeepAlive: 'yes'
        UseDNS: 'no'
        UsePAM: 'no'
        GatewayPorts: 'no'
        PermitTunnel: 'no'
        UsePrivilegeSeparation: 'sandbox'
        X11DisplayOffset: 10
        X11Forwarding: 'no'
        AllowAgentForwarding: 'no'
        AllowUsers: 'root'
        AllowGroups: 'root'
        # Cipher settings from https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Modern_.28OpenSSH_6.7.2B.29
        KexAlgorithms: 'curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
        Ciphers: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
        MACs: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  
        # If you want to use LDAP
        #AuthorizedKeysCommand: /etc/ssh/authorized_keys_command
        #AuthorizedKeysCommand_user: nobody
        #UsePAM: yes
  
  
      ssh_ssh_config:
        '*':
          SendEnv: 'LANG LC_*'
          HashKnownHosts: yes
          GSSAPIAuthentication: yes
  
      ssh_users:
  
          # name of the (existing!) user
        - name: root
  
          # name of the users primary group (for templating files)
          # TODO can we run this to determine it in loops?
          # /usr/bin/id -g -n root 2>/dev/null || echo root
          # Default: "name"
          group: root
  
          # Ansible is to retarded to determine a users home directory, hence...
          home: /root
  
          # Generate a ed25519 and rsa keypair, default: false
          generate_keypair: true
  
          # Setup key=value environment variables in ~/.ssh/environment
          environment:
            SOME: VARIABLE
  
          # Manage $HOME/.ssh/config
          config:
            'sat.github.com':
              HostName: 'github.com'
              User: git
              IdentityFile: '~/.ssh/id_ed25519'
              IdentitiesOnly: 'yes'
  
          # Populate authorized_keys
          authorized_keys:
            # - key: https://github.com/charlie.keys
            #   options: 'no-port-forwarding,from="10.0.1.1"'
            # - key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
            #   # present or absent, default: present
            #   state: present
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDce1PADdNqFq0OtHxS24O8YNZVciECEHXX3oTtdDTqgEuUUgW2+WFl7yQ3+HC8cv0JrrcIb/9qH0xtJiQ4eWliuRaTiquiMWo576oUVOSUhb8gCzpJIqGXL7auiDeHKT3JDbJpKFWop3y1e5pm6GHapQDY9UyZBO9cwXtpiQ/AKHy7U6J+BoLVPpVCpvAu5dwmUcnsYc/1Rs0MNwsIpc2V6qX3K9oEtkYYpxTR9tgM59bgMbwt+t2Wn//nFdykuRZqOYst7M1l1OamSio7VJPk5tMEM+l4TZvArAH+uARZoMI5VEilIE3mxJQKuv1OFwYDNjuFUur40MDBCdVvyq3n2REiz0lgR0pycgt4p7IQSWTQ1QtUexkIqGqE+tNy5Hn9Tv4SX71hiZQCVfQjv9aPkyQOiQVbte4YbDaxU/uI/8n18jaZtIsvsuYOruLsqYCu0qJgMrFg86tEELoYpW7hq1BixJPjmzwAi9GinRNF1DLaDpXPTY/vNdocUPwDF7Rdlbt6SrtHZ4/TlcxK49vC4lndblYmOZ5mIS1N6RdQNrnMHulPVhYRKpqhefFD077P4Ln/Esb5gBxsFdF+AqpBkbEt57vo+WsUXxN6LwNyub+zWSkN+Ne7Eam8PzBWBdPGZrVUr+HdyQk4rbSn5ucknj7mgbiwwX5oJcQFhKMN+w== p.thurner@blunix.org"
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7mZjoFnz5+kevKgC7Z+SurxSLkJ4juPHkf4KBm1r962q9UeNOJQJJy1q0Yg6nW9vUtheqGE+pnQ4lFUgIhWktIkKf0D9CGrUt5JYoRgcXhODKV59gFMtacLWe6sn2J5bZqLjIVAD2lUsgUspIo1RdFkxDN+FfHipULuPh08g50xAh69ZmCBrLCQl8aM8La8PZOHEzgDALcABVsssFo/K/KT3YE1Dq3lMk6GDW4W08B/VrbAE00wMuZIzB9np027InxFdDnwHhKqR7G5Wo2b7rgo5uB7Ds+lF82ZlDxaGlHIpkkahgNaWc+E5caiBxEe2BOz+3LvtsujIZXr76kmLF roland.geng@zielbewusst.net"
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvtfRsiy6lEuUTPVEMleBY3QOMUIVMPz3G9ssl8KdK9jq36ARmefx/jYSRwuFUbPrLnL+2Npdf5EmRMNM0ZC0JyL5kh+vU7AN36UFsATOVYFeHKUbPKV4eC5FtKvnI+m/QQWhQGQA1y3+WPwlzdDrN7Y8Mv6kysewAXQ3KBT6fQzXPVDFZpfWRH5EzS0/SArGaRsJobjGsxIS7VEgf79vL5mDFVJ081L4oKG28ITkkju5KYnTtZAGuQo3PkU1hNY1cvI5EKXMuXsw+ACrIS5Ri8Q+lr64iSuTEG/22ijQ6FJPd1MoTgqvZxrd3dIo2BSMhlg2PpeZPePKUWv8rY+1LQ== peter.koenig@zielbewusst.net"
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhbGd+mj4Etuy7M6wAvcEu5Uc5FFT+q0elXUGKCDrqA9PJGStsWzshLKJLAeFcvrxub/yzc0vJ2TzKP9yjZsmwVypVHdR12hsEM3no3wvBTnjvlJayQw9l2iCxEhtPv0jIbvaVqCt5Jeg/3A7MT9aXweGzRjey6EZYhclKhs/UCKxUXbaIKkJ7mKicD5EPKXCfcFRLO9WOAVr4zKZDpaS7qYIYheRMa69iP4TBh9fXN1HBPrh2nVVYBG+cWQJf/re+D36cTwQR7EtfBLf35aaUaIyM56yeBOv+XncpFDRydajGO+NSzf10/hBsBndIc3MHmQ8bYuhz7ua0mKy5qNl+42V/qcVeTC12YksmLdaorga+tp0jWoAcP1IxBw1An3QcGhRCfQ+lfZgH5KNE83+ami7AGaHwtTRoH2m4e/EQG/dHepqvjaXpHMkHNlGXhdKjzbphRdZ4sFE0o+/ASEdG0lfiFYcbEkJ/xwKlxAuHnzOv5gzMrJ6zDMD1GiG57wuRis+GKkVISkw/Bv1KtjXzZxEgs4a4TZE1SMy7J3fkrb1wysCj1r7Hk4xVmo7aEeckFNy+QCs1mhdK8IVPhrVtZC8UXQMmJRICmPczjJf0M8s5KlxUA7c8g0/aamffT9AzNzN+qINob4G+CXsVH5c41tS80rauFhUogVWY1PUSNw== falko.matthies@fincallorca.de"
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwxdLJQgXr+OVHuDQB7Dl0QOz++hws3jhciBb1nZqc8MwxcMZTAnINOHP4hG/CIuOBGyJcYwBaUplCHpg/1wuusf8ja3Xywkzu4RncvVlvNS7FoqgGH4ozV8x1tMGmPL42EPpFgiugjTOnc7GRBk622i6KHFdNBpZp4fbUOAj4kVXr8Sc+rm8sg8azoG2L1o4B1b4lakyKPX873uSnbnsS21zNIKRwO6wQonSw6W9uzNgz1jwyKtFzp9MFehhIUKnXoV1cF0TN41khRmKC9ImwW4KPiwfZ98ZDiHsidEHAmWvpz4lF8p9Vjh8olXoef640T7QyM4UTAs56ldsVBVi5Q== miroslav.koula@fincallorca.de"
  
          # Accept host keys to known_hosts
          known_hosts:
            - github.com
            - gitlab.com
            - 10.0.0.10
  
  
        # Minimal config - just add ssh authorized_keys
        - name: test
          home: /home/test
          authorized_keys:
            - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDce1PADdNqFq0OtHxS24O8YNZVciECEHXX3oTtdDTqgEuUUgW2+WFl7yQ3+HC8cv0JrrcIb/9qH0xtJiQ4eWliuRaTiquiMWo576oUVOSUhb8gCzpJIqGXL7auiDeHKT3JDbJpKFWop3y1e5pm6GHapQDY9UyZBO9cwXtpiQ/AKHy7U6J+BoLVPpVCpvAu5dwmUcnsYc/1Rs0MNwsIpc2V6qX3K9oEtkYYpxTR9tgM59bgMbwt+t2Wn//nFdykuRZqOYst7M1l1OamSio7VJPk5tMEM+l4TZvArAH+uARZoMI5VEilIE3mxJQKuv1OFwYDNjuFUur40MDBCdVvyq3n2REiz0lgR0pycgt4p7IQSWTQ1QtUexkIqGqE+tNy5Hn9Tv4SX71hiZQCVfQjv9aPkyQOiQVbte4YbDaxU/uI/8n18jaZtIsvsuYOruLsqYCu0qJgMrFg86tEELoYpW7hq1BixJPjmzwAi9GinRNF1DLaDpXPTY/vNdocUPwDF7Rdlbt6SrtHZ4/TlcxK49vC4lndblYmOZ5mIS1N6RdQNrnMHulPVhYRKpqhefFD077P4Ln/Esb5gBxsFdF+AqpBkbEt57vo+WsUXxN6LwNyub+zWSkN+Ne7Eam8PzBWBdPGZrVUr+HdyQk4rbSn5ucknj7mgbiwwX5oJcQFhKMN+w== p.thurner@blunix.org"
