- name: install OpenSSH server
  apt:
    name:
      - openssh-server
      # For Ansible become
      - acl
    state: present

- name: configure /etc/ssh/sshd_config.d/ansible.conf
  template:
    src: etc/ssh/sshd_config.d/ansible.conf.j2
    dest: /etc/ssh/sshd_config.d/ansible.conf
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
  tags:
    - config

- name: configure /etc/ssh/ssh_config.d/ansible.conf
  template:
    src: etc/ssh/ssh_config.d/ansible.conf.j2
    dest: /etc/ssh/ssh_config.d/ansible.conf
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
  tags:
    - config

- name: create admins group
  group:
    name: admins
    gid: 20000
  tags:
    - user

- name: "include tasks to manage user {{ ssh_user['name'] }}"
  include_tasks: users/manage.yml
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user
  when: ssh_user['state'] | default('present') != 'absent'
  tags:
    - user

- name: "include tasks to remove user {{ ssh_user['name'] }}"
  include_tasks: users/remove.yml
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user
  when: ssh_user['state'] | default('present') == 'absent'
  tags:
    - user
