---
- name: include OS-specific vars for SSH
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
    - "{{ ansible_distribution }}.yml"

- include: "{{ distro_installer }}"
  with_first_found:
    - "install/{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
    - "install/{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: distro_installer

- include: "{{ distro_configurator }}"
  with_first_found:
    - "configure/{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
    - "configure/{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: distro_configurator

- include: configure/authorized_keys_command.yml
