---
- name: Converge
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: True
      changed_when: False

- name: Converge
  hosts: all
  become: yes
  vars:
    slapd_basedn: dc=example,dc=com
    ssh_enabled: yes
    ssh_sshd_config_listen_addresses:
      - 0.0.0.0
    ssh_use_ldap: yes
    ssh_ldap_key_auth: yes
    ssh_ldap_binddn: cn=sshd,ou=users,{{ slapd_basedn }}
    ssh_ldap_bindpw: ldap
    ssh_sshd_config_host_keys:
      - /etc/ssh/ssh_host_rsa_key
      - /etc/ssh/ssh_host_ecdsa_key
      - /etc/ssh/ssh_host_ed25519_key
    ssh_sshd_config_use_privilege_separation: 'yes'
    ssh_sshd_config_syslog_facility: AUTH
    ssh_sshd_config_login_grace_time: 120
    ssh_sshd_config_ignore_rhosts: 'yes'
    ssh_sshd_config_host_based_authentication: 'no'
    ssh_sshd_config_challenge_response_authentication: 'no'
    ssh_sshd_config_use_pam: 'yes'
    ssh_sshd_config_use_dns: 'no'
    ssh_sshd_config_authorized_keys_command: /etc/ssh/authorized_keys_command
    ssh_sshd_config_authorized_keys_command_user: nobody
    ssh_sshd_config_log_level: INFO
    ssh_sshd_config_permit_root_login: prohibit-password
    ssh_sshd_config_strict_mode: 'yes'
    ssh_sshd_config_allow_agent_forwarding: 'no'
    ssh_sshd_gateway_ports: 'no'
    ssh_sshd_x11_forwarding: 'no'
    ssh_sshd_config_permit_tunnel: 'no'
    ssh_sshd_config_kex_algorithms: 'curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
    ssh_sshd_config_ciphers: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
    ssh_sshd_config_macs: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'

  roles:
    - role: role-ssh
