---
- name: configure sshd_config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: include templating of authorized_keys
  include_tasks: authorized_keys.yml
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user

- name: generate ssh keypairs for users
  shell: |
      ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519 -N ''
      ssh-keygen -t rsa -b 4096 -o -a 100 -f ~/.ssh/id_rsa -N ''
      chmod 600 ~/.ssh/*
  args:
    creates: "{{ ssh_user['home'] }}/.ssh/id_rsa"
  become: yes
  become_user: "{{ ssh_user['name'] }}"
  when: ssh_user['generate_keypair'] == true
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user
  register: ssh_user_keypair_generation_output
# - debug:
#     msg: "{{ ssh_user_keypair_generation_output.stdout_lines }}"
# TODO bugs around, I assume because the above task is a loop
# Task above works as expected though

- name: template ~/.ssh/environment
  template:
    src: home/user/.ssh/environment.j2
    dest: "{{ ssh_user['home'] }}/.ssh/environment"
    owner: "{{ ssh_user['name'] }}"
    group: "{{ ssh_user['group'] | default(ssh_user['name']) }}"
    mode: 0600
  become: yes
  become_user: "{{ ssh_user['name'] }}"
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user

- name: template ~/.ssh/config
  template:
    src: home/user/.ssh/config.j2
    dest: "{{ ssh_user['home'] }}/.ssh/config"
    owner: "{{ ssh_user['name'] }}"
    group: "{{ ssh_user['group'] | default(ssh_user['name']) }}"
    mode: 0600
  become: yes
  become_user: "{{ ssh_user['name'] }}"
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user

- name: include accepting host keys to known_hosts
  include_tasks: known_hosts.yml
  with_items: "{{ ssh_users }}"
  loop_control:
    loop_var: ssh_user
