# TODO this breaks the idempotency tests
# TODO succeeds even when host is not known
- name: accept ssh host keys to known_hosts
  shell: "ssh -o HashKnownHosts=no -o StrictHostKeyChecking=no {{ ssh_user_known_host }} /bin/true || /bin/true"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ ssh_user['name'] }}"
  when: ssh_user['state'] | default('present') != 'absent'
  with_items: "{{ ssh_user['known_hosts'] }}"
  loop_control:
    loop_var: ssh_user_known_host

